# Generated by Django 4.0.4 on 2022-07-21 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('salon_name', models.CharField(blank=True, max_length=200, null=True)),
                ('salon_rows', models.IntegerField()),
                ('salon_columns', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.movie')),
            ],
            options={
                'ordering': ['-rows'],
            },
        ),
    ]
