# Generated by Django 4.0.4 on 2022-07-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_movie_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezervation',
            options={'ordering': ['-rows']},
        ),
    ]
